#!/bin/bash

term=`ps gaxu | grep -v grep | grep $0 | awk '{print $7}' | tail -n 1`
term_size=`stty -F "/dev/$term" size | grep -Eio "[0-9]+$"`
#term_size=`stty size | grep -Eio "[0-9]+$"`
let term_size=$term_size-3 # removing one more char than we need to because of echo behavior in cygwin.
numer=$1

if [ -z "$numer" ]; then
  exit -1
elif [ "$numer" -lt 0 ]; then
  exit 1
fi

denom=100
if [ "$2" ]; then
  denom=$2
fi

# terminals can't print partial chars, so may as well just work with whole numbers.
let pct=($numer*100)/$denom
let bar_size=($term_size*$pct)/100

bar_ct=0
bar=''
while [ $bar_ct -lt $bar_size ]
do
  bar="$bar="
  let bar_ct=$bar_ct+1
done

bar="$bar>"
while [ $bar_ct -lt $term_size ]
do
  bar="$bar."
  let bar_ct=$bar_ct+1
done

echo -en "$bar]\r[$pct%\r"
